/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.CidadeController;
import controller.PTuristicoController;
import controller.RestauranteController;
import controller.FundadorController;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.entity.Cidade;
import model.entity.Restaurante;
import model.entity.Fundador;

/**
 *
 * @author User
 */
public class AddPTuristico extends javax.swing.JPanel {

    /**
     * Creates new form AddPTuristico
     */
    public AddPTuristico() {
        initComponents();
        jCBCidade.setModel(new DefaultComboBoxModel<>());
        jCBCasashowRestaurante.setModel(new DefaultComboBoxModel<>());
        jCBMuseuFundadores.setModel(new DefaultComboBoxModel<>());
    }
    
    private void loadCidade(){
        getjCBCidade().removeAllItems();
        for(Cidade item: new CidadeController().loadAllCidade()){
            getjCBCidade().addItem(item);
        }
    }
    
    private void loadRestaurante(){
        Cidade cd = (Cidade) getjCBCidade().getSelectedItem();
        if(cd == null){
            cd = getjCBCidade().getItemAt(0);
        }
        getjCBCasashowRestaurante().removeAllItems();
        for(Restaurante item: new RestauranteController().loadAllRestaurante(cd)){
            getjCBCasashowRestaurante().addItem(item);
        }
    }
    
    private void loadFundador(){
        getjCBMuseuFundadores().removeAllItems();
        for(Fundador item: new FundadorController().loadAllFundador()){
            getjCBMuseuFundadores().addItem(item);
        }
    }
    
    private void limparCasaShow(){
        getjTFCasashowHrinicio().setText("");
        try{
            getjCBCasashowRestaurante().setSelectedIndex(0);
        }catch(IllegalArgumentException e){}
        try{
            getjCBCasashowDiafech().setSelectedIndex(0);
        }catch(IllegalArgumentException e){}
        try{
            getjCBCasashowEsp().setSelectedIndex(0);
        }catch(IllegalArgumentException e){}
        jCkBCasashowRestaurante.setSelected(false);
        getjTFCasashowPreco().setText("");
        getjTFCasashowPreco().setEnabled(false);
        getjCBCasashowEsp().setEnabled(false);
        getjCBCasashowRestaurante().setEnabled(false);
    }
    
    private void limparIgreja(){
        getjTFIgrejaEstilo().setText("");
        getjTFIgrejaData().setText("");
    }
    
    private void limparMuseu(){
        getjTFMuseuData().setText("");
        getjTFMuseuNrsalas().setText("");
        getjLtMuseuFundadores().setModel(new DefaultListModel<>());
        try{
            getjCBMuseuFundadores().setSelectedIndex(0);
        }catch(IllegalArgumentException e){}
    }
    
    private void limparParque(){
        getjTFParqueNrAtracoes().setText("");
        getjTFParqueCapacidade().setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLInserir = new javax.swing.JLabel();
        jBConcluir = new javax.swing.JButton();
        jRBCasaShow = new javax.swing.JRadioButton();
        jRBParque = new javax.swing.JRadioButton();
        jRBMuseu = new javax.swing.JRadioButton();
        jRBIgreja = new javax.swing.JRadioButton();
        jPPturistico = new javax.swing.JPanel();
        jPCasashow = new javax.swing.JPanel();
        jLCasashowHrinicio = new javax.swing.JLabel();
        jTFCasashowHrinicio = new javax.swing.JTextField();
        jLCasashowDiafech = new javax.swing.JLabel();
        jCBCasashowDiafech = new javax.swing.JComboBox<>();
        jLCasashowRestaurante = new javax.swing.JLabel();
        jCBCasashowRestaurante = new javax.swing.JComboBox<>();
        jCkBCasashowRestaurante = new javax.swing.JCheckBox();
        jLCasashowPreco = new javax.swing.JLabel();
        jTFCasashowPreco = new javax.swing.JTextField();
        jLCasashowEsp = new javax.swing.JLabel();
        jCBCasashowEsp = new javax.swing.JComboBox<>();
        jPIgreja = new javax.swing.JPanel();
        jLIgrejaData = new javax.swing.JLabel();
        jLIgrejaEstilo = new javax.swing.JLabel();
        jTFIgrejaData = new javax.swing.JTextField();
        jTFIgrejaEstilo = new javax.swing.JTextField();
        jPMuseu = new javax.swing.JPanel();
        jLMuseuData = new javax.swing.JLabel();
        jLMuseuNrsalas = new javax.swing.JLabel();
        jTFMuseuNrsalas = new javax.swing.JTextField();
        jTFMuseuData = new javax.swing.JTextField();
        jLMuseuFundadores = new javax.swing.JLabel();
        jCBMuseuFundadores = new javax.swing.JComboBox<>();
        jBMuseuAdicionar = new javax.swing.JButton();
        jSPMuseuFundadores = new javax.swing.JScrollPane();
        jLtMuseuFundadores = new javax.swing.JList(new javax.swing.DefaultListModel<Fundador>());
        jBMuseuRemover = new javax.swing.JButton();
        jPParque = new javax.swing.JPanel();
        jLParqueNratracoes = new javax.swing.JLabel();
        jLParqueCapacidade = new javax.swing.JLabel();
        jTFParqueNrAtracoes = new javax.swing.JTextField();
        jTFParqueCapacidade = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        jLCidade = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jSPDescricao = new javax.swing.JScrollPane();
        jTADescricao = new javax.swing.JTextArea();
        jTFNome = new javax.swing.JTextField();
        jTFEndereco = new javax.swing.JTextField();
        jCBCidade = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jBLimpar = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLInserir.setText("Inserir Ponto Turístico");

        jBConcluir.setText("Concluir");
        jBConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcluirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBCasaShow);
        jRBCasaShow.setSelected(true);
        jRBCasaShow.setText("Casa de Show");
        jRBCasaShow.setActionCommand("casashow");
        jRBCasaShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasaShowActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBParque);
        jRBParque.setText("Parque");
        jRBParque.setActionCommand("parque");
        jRBParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBParqueActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBMuseu);
        jRBMuseu.setText("Museu");
        jRBMuseu.setActionCommand("museu");
        jRBMuseu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMuseuActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBIgreja);
        jRBIgreja.setText("Igreja");
        jRBIgreja.setActionCommand("igreja");
        jRBIgreja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIgrejaActionPerformed(evt);
            }
        });

        jPPturistico.setLayout(new java.awt.CardLayout());

        jPCasashow.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPCasashowComponentHidden(evt);
            }
        });

        jLCasashowHrinicio.setText("Hora de início:");

        jTFCasashowHrinicio.setToolTipText("hh:mm");

        jLCasashowDiafech.setText("Dia de fechamento:");

        jCBCasashowDiafech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SAB" }));

        jLCasashowRestaurante.setText("Restaurante:");

        jCBCasashowRestaurante.setEnabled(false);

        jCkBCasashowRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCkBCasashowRestauranteActionPerformed(evt);
            }
        });

        jLCasashowPreco.setText("Preço médio:");

        jTFCasashowPreco.setToolTipText("Valor decimal com ponto, como 24.99");
        jTFCasashowPreco.setEnabled(false);

        jLCasashowEsp.setText("Especialidade:");

        jCBCasashowEsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUTRO", "BRA", "ITA", "JAP", "MEX" }));
        jCBCasashowEsp.setEnabled(false);

        javax.swing.GroupLayout jPCasashowLayout = new javax.swing.GroupLayout(jPCasashow);
        jPCasashow.setLayout(jPCasashowLayout);
        jPCasashowLayout.setHorizontalGroup(
            jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasashowLayout.createSequentialGroup()
                .addGroup(jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCasashowHrinicio)
                    .addComponent(jLCasashowRestaurante)
                    .addComponent(jLCasashowPreco))
                .addGap(18, 18, 18)
                .addGroup(jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBCasashowRestaurante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPCasashowLayout.createSequentialGroup()
                        .addGroup(jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCasashowLayout.createSequentialGroup()
                                .addComponent(jTFCasashowHrinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLCasashowDiafech)
                                .addGap(18, 18, 18)
                                .addComponent(jCBCasashowDiafech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCasashowLayout.createSequentialGroup()
                                .addComponent(jTFCasashowPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLCasashowEsp)
                                .addGap(18, 18, 18)
                                .addComponent(jCBCasashowEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCkBCasashowRestaurante))
        );
        jPCasashowLayout.setVerticalGroup(
            jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasashowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCasashowHrinicio)
                    .addComponent(jTFCasashowHrinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCasashowDiafech)
                    .addComponent(jCBCasashowDiafech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCasashowRestaurante)
                        .addComponent(jCBCasashowRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCkBCasashowRestaurante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCasashowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCasashowPreco)
                    .addComponent(jTFCasashowPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCasashowEsp)
                    .addComponent(jCBCasashowEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPturistico.add(jPCasashow, "addcasashow");

        jPIgreja.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPIgrejaComponentHidden(evt);
            }
        });

        jLIgrejaData.setText("Data de Fundação:");

        jLIgrejaEstilo.setText("Estilo de Construção:");

        jTFIgrejaData.setToolTipText("dd/mm/aaaa");

        javax.swing.GroupLayout jPIgrejaLayout = new javax.swing.GroupLayout(jPIgreja);
        jPIgreja.setLayout(jPIgrejaLayout);
        jPIgrejaLayout.setHorizontalGroup(
            jPIgrejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIgrejaLayout.createSequentialGroup()
                .addComponent(jLIgrejaData)
                .addGap(18, 18, 18)
                .addComponent(jTFIgrejaData, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLIgrejaEstilo)
                .addGap(18, 18, 18)
                .addComponent(jTFIgrejaEstilo, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPIgrejaLayout.setVerticalGroup(
            jPIgrejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIgrejaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPIgrejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIgrejaData)
                    .addComponent(jTFIgrejaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIgrejaEstilo)
                    .addComponent(jTFIgrejaEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPPturistico.add(jPIgreja, "addigreja");

        jPMuseu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPMuseuComponentHidden(evt);
            }
        });

        jLMuseuData.setText("Data de Fundação:");

        jLMuseuNrsalas.setText("Número de Salas:");

        jTFMuseuData.setToolTipText("dd/mm/aaaa");

        jLMuseuFundadores.setText("Fundadores:");

        jBMuseuAdicionar.setText("Adicionar");
        jBMuseuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMuseuAdicionarActionPerformed(evt);
            }
        });

        jLtMuseuFundadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jSPMuseuFundadores.setViewportView(jLtMuseuFundadores);

        jBMuseuRemover.setText("Remover");
        jBMuseuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMuseuRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMuseuLayout = new javax.swing.GroupLayout(jPMuseu);
        jPMuseu.setLayout(jPMuseuLayout);
        jPMuseuLayout.setHorizontalGroup(
            jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMuseuLayout.createSequentialGroup()
                .addGroup(jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMuseuData)
                    .addComponent(jLMuseuFundadores))
                .addGap(18, 18, 18)
                .addGroup(jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMuseuLayout.createSequentialGroup()
                        .addComponent(jTFMuseuData, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLMuseuNrsalas)
                        .addGap(18, 18, 18)
                        .addComponent(jTFMuseuNrsalas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPMuseuLayout.createSequentialGroup()
                        .addGroup(jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSPMuseuFundadores, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(jCBMuseuFundadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBMuseuAdicionar)
                            .addComponent(jBMuseuRemover)))))
        );
        jPMuseuLayout.setVerticalGroup(
            jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMuseuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMuseuData)
                    .addComponent(jTFMuseuData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMuseuNrsalas)
                    .addComponent(jTFMuseuNrsalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMuseuFundadores)
                    .addComponent(jCBMuseuFundadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMuseuAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMuseuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSPMuseuFundadores, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMuseuRemover))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPPturistico.add(jPMuseu, "addmuseu");

        jPParque.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPParqueComponentHidden(evt);
            }
        });

        jLParqueNratracoes.setText("Número de Atrações:");

        jLParqueCapacidade.setText("Capacidade:");

        javax.swing.GroupLayout jPParqueLayout = new javax.swing.GroupLayout(jPParque);
        jPParque.setLayout(jPParqueLayout);
        jPParqueLayout.setHorizontalGroup(
            jPParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPParqueLayout.createSequentialGroup()
                .addComponent(jLParqueNratracoes)
                .addGap(18, 18, 18)
                .addComponent(jTFParqueNrAtracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLParqueCapacidade)
                .addGap(18, 18, 18)
                .addComponent(jTFParqueCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPParqueLayout.setVerticalGroup(
            jPParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPParqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLParqueNratracoes)
                    .addComponent(jTFParqueNrAtracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLParqueCapacidade)
                    .addComponent(jTFParqueCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPPturistico.add(jPParque, "addparque");

        jLTipo.setText("Tipo:");

        jLNome.setText("Nome:");

        jLDescricao.setText("Descrição:");

        jLCidade.setText("Cidade:");

        jLEndereco.setText("Endereço:");

        jTADescricao.setColumns(20);
        jTADescricao.setRows(5);
        jSPDescricao.setViewportView(jTADescricao);

        jTFEndereco.setToolTipText("Rua, Número, Bairro");

        jCBCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCidadeItemStateChanged(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPPturistico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDescricao)
                                    .addComponent(jLCidade)
                                    .addComponent(jLEndereco)
                                    .addComponent(jLTipo)
                                    .addComponent(jLNome))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBCasaShow)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBIgreja)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBMuseu)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBParque)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSPDescricao)
                                    .addComponent(jTFEndereco)
                                    .addComponent(jCBCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFNome)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLInserir)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBConcluir)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLInserir)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCidade)
                    .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndereco)
                    .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBCasaShow)
                    .addComponent(jRBMuseu)
                    .addComponent(jRBIgreja)
                    .addComponent(jRBParque)
                    .addComponent(jLTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPturistico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConcluir)
                    .addComponent(jBLimpar))
                .addGap(130, 130, 130))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcluirActionPerformed
        String message = "Ponto Turístico inserido com sucesso!";
        String title = "Sucesso";
        int type = JOptionPane.INFORMATION_MESSAGE;
        try{
            new PTuristicoController().addPTuristico(this);
        }catch(Exception e){
            message = "Ocorreu um erro ao inserir o ponto turístico...\n\n" + e.getMessage().split("\n")[0];
            title = "Erro";
            type = JOptionPane.ERROR_MESSAGE;
            e.printStackTrace();
        }finally{
            JOptionPane.showMessageDialog(null,message,title,type);
        }
    }//GEN-LAST:event_jBConcluirActionPerformed

    private void jRBCasaShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasaShowActionPerformed
        java.awt.CardLayout c = (java.awt.CardLayout)(jPPturistico.getLayout());
        c.show(jPPturistico, "addcasashow");
    }//GEN-LAST:event_jRBCasaShowActionPerformed

    private void jRBIgrejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIgrejaActionPerformed
        java.awt.CardLayout c = (java.awt.CardLayout)(jPPturistico.getLayout());
        c.show(jPPturistico, "addigreja");
    }//GEN-LAST:event_jRBIgrejaActionPerformed

    private void jRBMuseuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMuseuActionPerformed
        java.awt.CardLayout c = (java.awt.CardLayout)(jPPturistico.getLayout());
        c.show(jPPturistico, "addmuseu");
    }//GEN-LAST:event_jRBMuseuActionPerformed

    private void jRBParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBParqueActionPerformed
        java.awt.CardLayout c = (java.awt.CardLayout)(jPPturistico.getLayout());
        c.show(jPPturistico, "addparque");
    }//GEN-LAST:event_jRBParqueActionPerformed

    private void jCkBCasashowRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCkBCasashowRestauranteActionPerformed
        boolean value = getjCBCasashowRestaurante().isEnabled();
        getjCBCasashowRestaurante().setSelectedIndex(0);
        getjCBCasashowRestaurante().setEnabled(!value);
        getjCBCasashowEsp().setSelectedIndex(0);
        getjCBCasashowEsp().setEnabled(!value);
        getjTFCasashowPreco().setText("");
        getjTFCasashowPreco().setEnabled(!value);
    }//GEN-LAST:event_jCkBCasashowRestauranteActionPerformed

    private void jBMuseuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMuseuAdicionarActionPerformed
        Fundador selected = (Fundador) getjCBMuseuFundadores().getSelectedItem();
        DefaultListModel<Fundador> list = (DefaultListModel<Fundador>) getjLtMuseuFundadores().getModel();
        if(!list.contains(selected)){
            list.addElement(selected);
        }
        getjLtMuseuFundadores().setModel(list);
    }//GEN-LAST:event_jBMuseuAdicionarActionPerformed

    private void jBMuseuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMuseuRemoverActionPerformed
        int index = getjLtMuseuFundadores().getSelectedIndex();
        DefaultListModel<Fundador> list = (DefaultListModel<Fundador>) getjLtMuseuFundadores().getModel();
        if (index != -1){
            list.remove(index);
        }
        getjLtMuseuFundadores().setModel(list);
    }//GEN-LAST:event_jBMuseuRemoverActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadCidade();
        loadFundador();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        getjCBCidade().removeAllItems();
        getjCBCasashowRestaurante().removeAllItems();
        getjCBMuseuFundadores().removeAllItems();
    }//GEN-LAST:event_formComponentHidden

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        getjTFNome().setText("");
        getjTADescricao().setText("");
        getjTFEndereco().setText("");
        jRBCasaShow.doClick();
        limparCasaShow();
        try{
            getjCBCidade().setSelectedIndex(0);
        }catch(IllegalArgumentException e){}
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jPCasashowComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPCasashowComponentHidden
        limparCasaShow();
    }//GEN-LAST:event_jPCasashowComponentHidden

    private void jPIgrejaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPIgrejaComponentHidden
        limparIgreja();
    }//GEN-LAST:event_jPIgrejaComponentHidden

    private void jPMuseuComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPMuseuComponentHidden
        limparMuseu();
    }//GEN-LAST:event_jPMuseuComponentHidden

    private void jPParqueComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPParqueComponentHidden
        limparParque();
    }//GEN-LAST:event_jPParqueComponentHidden

    private void jCBCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCidadeItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            if(getjCkBCasashowRestaurante().isSelected()){
                getjCkBCasashowRestaurante().doClick();
            }
            loadRestaurante();
            getjCkBCasashowRestaurante().setEnabled(getjCBCasashowRestaurante().getModel().getSize() != 0);
        }
    }//GEN-LAST:event_jCBCidadeItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBConcluir;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBMuseuAdicionar;
    private javax.swing.JButton jBMuseuRemover;
    private javax.swing.JComboBox<String> jCBCasashowDiafech;
    private javax.swing.JComboBox<String> jCBCasashowEsp;
    private javax.swing.JComboBox<Restaurante> jCBCasashowRestaurante;
    private javax.swing.JComboBox<Cidade> jCBCidade;
    private javax.swing.JComboBox<Fundador> jCBMuseuFundadores;
    private javax.swing.JCheckBox jCkBCasashowRestaurante;
    private javax.swing.JLabel jLCasashowDiafech;
    private javax.swing.JLabel jLCasashowEsp;
    private javax.swing.JLabel jLCasashowHrinicio;
    private javax.swing.JLabel jLCasashowPreco;
    private javax.swing.JLabel jLCasashowRestaurante;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLIgrejaData;
    private javax.swing.JLabel jLIgrejaEstilo;
    private javax.swing.JLabel jLInserir;
    private javax.swing.JLabel jLMuseuData;
    private javax.swing.JLabel jLMuseuFundadores;
    private javax.swing.JLabel jLMuseuNrsalas;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLParqueCapacidade;
    private javax.swing.JLabel jLParqueNratracoes;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JList<Fundador> jLtMuseuFundadores;
    private javax.swing.JPanel jPCasashow;
    private javax.swing.JPanel jPIgreja;
    private javax.swing.JPanel jPMuseu;
    private javax.swing.JPanel jPParque;
    private javax.swing.JPanel jPPturistico;
    private javax.swing.JRadioButton jRBCasaShow;
    private javax.swing.JRadioButton jRBIgreja;
    private javax.swing.JRadioButton jRBMuseu;
    private javax.swing.JRadioButton jRBParque;
    private javax.swing.JScrollPane jSPDescricao;
    private javax.swing.JScrollPane jSPMuseuFundadores;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTADescricao;
    private javax.swing.JTextField jTFCasashowHrinicio;
    private javax.swing.JTextField jTFCasashowPreco;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFIgrejaData;
    private javax.swing.JTextField jTFIgrejaEstilo;
    private javax.swing.JTextField jTFMuseuData;
    private javax.swing.JTextField jTFMuseuNrsalas;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFParqueCapacidade;
    private javax.swing.JTextField jTFParqueNrAtracoes;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public javax.swing.JComboBox<String> getjCBCasashowDiafech() {
        return jCBCasashowDiafech;
    }

    public javax.swing.JComboBox<String> getjCBCasashowEsp() {
        return jCBCasashowEsp;
    }

    public javax.swing.JComboBox<Restaurante> getjCBCasashowRestaurante() {
        return jCBCasashowRestaurante;
    }

    public javax.swing.JComboBox<Cidade> getjCBCidade() {
        return jCBCidade;
    }

    public javax.swing.JComboBox<Fundador> getjCBMuseuFundadores() {
        return jCBMuseuFundadores;
    }

    public javax.swing.JCheckBox getjCkBCasashowRestaurante() {
        return jCkBCasashowRestaurante;
    }

    public javax.swing.JTextArea getjTADescricao() {
        return jTADescricao;
    }

    public javax.swing.JTextField getjTFCasashowHrinicio() {
        return jTFCasashowHrinicio;
    }

    public javax.swing.JTextField getjTFCasashowPreco() {
        return jTFCasashowPreco;
    }

    public javax.swing.JTextField getjTFEndereco() {
        return jTFEndereco;
    }

    public javax.swing.JTextField getjTFIgrejaData() {
        return jTFIgrejaData;
    }

    public javax.swing.JTextField getjTFIgrejaEstilo() {
        return jTFIgrejaEstilo;
    }

    public javax.swing.JTextField getjTFMuseuData() {
        return jTFMuseuData;
    }

    public javax.swing.JTextField getjTFMuseuNrsalas() {
        return jTFMuseuNrsalas;
    }

    public javax.swing.JTextField getjTFNome() {
        return jTFNome;
    }

    public javax.swing.JTextField getjTFParqueCapacidade() {
        return jTFParqueCapacidade;
    }

    public javax.swing.JTextField getjTFParqueNrAtracoes() {
        return jTFParqueNrAtracoes;
    }
    
    public javax.swing.JList<Fundador> getjLtMuseuFundadores() {
        return jLtMuseuFundadores;
    }
    
    public java.util.ArrayList<Fundador> getjLtMuseuFundadoresAsList() {
        DefaultListModel<Fundador> model = (DefaultListModel<Fundador>) getjLtMuseuFundadores().getModel();
        int size = model.getSize();
        ArrayList<Fundador> list = new ArrayList<>();
        for(int i = 0; i < size; i++){
            list.add(model.elementAt(i));
        }
        return list;
    }
    
}

