/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class AppGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppGUI
     */
    public AppGUI() {
        initComponents();
        menu1.setPanelController(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        home1 = new view.Home();
        addContrato1 = new view.AddContrato();
        addCliente1 = new view.AddCliente();
        addPacote1 = new view.AddPacote();
        addHotel1 = new view.AddHotel();
        addRestaurante1 = new view.AddRestaurante();
        addPTuristico1 = new view.AddPTuristico();
        addCidade1 = new view.AddCidade();
        addFundador1 = new view.AddFundador();
        menu1 = new view.Menu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panel.setPreferredSize(new java.awt.Dimension(544, 480));
        panel.setLayout(new java.awt.CardLayout());
        panel.add(home1, "home");
        panel.add(addContrato1, "addcontrato");
        addContrato1.getAccessibleContext().setAccessibleName("");

        panel.add(addCliente1, "addcliente");
        panel.add(addPacote1, "addpacote");
        panel.add(addHotel1, "addhotel");
        panel.add(addRestaurante1, "addrestaurante");
        panel.add(addPTuristico1, "addpturistico");
        panel.add(addCidade1, "addcidade");
        panel.add(addFundador1, "addfundador");

        menu1.setPreferredSize(new java.awt.Dimension(170, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.AddCidade addCidade1;
    private view.AddCliente addCliente1;
    private view.AddContrato addContrato1;
    private view.AddFundador addFundador1;
    private view.AddHotel addHotel1;
    private view.AddPTuristico addPTuristico1;
    private view.AddPacote addPacote1;
    private view.AddRestaurante addRestaurante1;
    private view.Home home1;
    private view.Menu menu1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
