/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        upPacote1 = new view.UpPacote();
        upAtracoes1 = new view.UpAtracoes();
        upCliente1 = new view.UpCliente();
        upCidade1 = new view.UpCidade();
        upFundador1 = new view.UpFundador();

        setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setText("Novo PT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addTab("Pacotes", upPacote1);
        jTabbedPane1.addTab("Atrações", upAtracoes1);

        upCliente1.setName("Clientes"); // NOI18N
        jTabbedPane1.addTab("Clientes", upCliente1);
        jTabbedPane1.addTab("Cidades", upCidade1);
        jTabbedPane1.addTab("Fundadores", upFundador1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jTabbedPane1)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        try{
            ResultSet rs = Conexao.getConnection().prepareStatement("select * from parques").executeQuery();
            while(rs.next()){
                System.out.printf("nratr %d, cap %d\n",rs.getInt(2),rs.getInt(3));
            }
        }catch (SQLException e){
            System.err.println("foi de f");
        }
        */
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private view.UpAtracoes upAtracoes1;
    private view.UpCidade upCidade1;
    private view.UpCliente upCliente1;
    private view.UpFundador upFundador1;
    private view.UpPacote upPacote1;
    // End of variables declaration//GEN-END:variables
}
