/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ClienteController;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import model.entity.Cliente;

/**
 *
 * @author User
 */
public class UpCliente extends javax.swing.JPanel {

    
    /**
     * Creates new form addCliente
     */
    public UpCliente() {
        initComponents();
    }
    
    private void loadCliente(){
        getjCBClientes().removeAllItems();
        for(Cliente item: new ClienteController().loadAllCliente()){
            getjCBClientes().addItem(item);
        }
    }
    
    private void toggleEnabled(){
        boolean enabled = !getjTFNome().isEnabled();
        getjTFNome().setEnabled(enabled);
        getjTFDtnasc().setEnabled(enabled);
        getjTFEmail().setEnabled(enabled);
        getjTFEndereco().setEnabled(enabled);
        getjTFTelefone().setEnabled(enabled);
        jBSalvar.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jLNome = new javax.swing.JLabel();
        jLDtnasc = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLTelefone = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jTFEndereco = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jTFDtnasc = new javax.swing.JTextField();
        jCBClientes = new javax.swing.JComboBox<>();
        jBSalvar = new javax.swing.JButton();
        jCBPacotes = new javax.swing.JComboBox<>();
        jLPacotes = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLNome.setText("Nome Completo:");

        jLDtnasc.setText("Data de Nascimento:");

        jLEmail.setText("E-mail:");

        jLEndereco.setText("Endereço:");

        jLTelefone.setText("Telefone:");

        jTFNome.setEnabled(false);

        jTFEmail.setToolTipText("nome@email.com");
        jTFEmail.setEnabled(false);

        jTFEndereco.setToolTipText("Rua, Número, Bairro");
        jTFEndereco.setEnabled(false);

        jTFTelefone.setToolTipText("(xx) x xxxx-xxxx");
        jTFTelefone.setEnabled(false);

        jTFDtnasc.setToolTipText("dd/mm/aaaa");
        jTFDtnasc.setEnabled(false);

        jCBClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBClientesItemStateChanged(evt);
            }
        });

        jBSalvar.setText("Salvar");
        jBSalvar.setEnabled(false);
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jCBPacotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLPacotes.setText("Pacotes Comprados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBClientes, 0, 532, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEmail)
                            .addComponent(jLTelefone)
                            .addComponent(jLEndereco)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLDtnasc, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLNome))
                            .addComponent(jLPacotes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(jTFEmail)
                            .addComponent(jTFNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFDtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCBPacotes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEditar)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDtnasc)
                    .addComponent(jTFDtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEndereco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTelefone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPacotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPacotes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEditar)
                    .addComponent(jBExcluir)
                    .addComponent(jBSalvar))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        toggleEnabled();
        if(jBEditar.getText() == "Editar"){
            jBEditar.setText("Cancelar");
        }else{
            jBEditar.setText("Editar");
            new ClienteController().showCliente(this);
        }

    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        String message = "Confirmar exclusão do cliente";
        String title = "Exclusão";
        int type = JOptionPane.OK_CANCEL_OPTION;
        int response = JOptionPane.showConfirmDialog(null, message, title, type);
        if(response == 0){
            new ClienteController().deleteCliente(this);
            loadCliente();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        getjCBClientes().removeAllItems();
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadCliente();
    }//GEN-LAST:event_formComponentShown

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        String message = "Dados do cliente atualizados com sucesso!";
        String title = "Sucesso";
        int type = JOptionPane.INFORMATION_MESSAGE;
        try{
            new ClienteController().updateCliente(this);
            jBEditar.setText("Editar");
            toggleEnabled();
        }catch(DateTimeParseException e){
            message = "O formato da data está incorreto. (dd/mm/aaaa)";
            title = "Erro";
            type = JOptionPane.ERROR_MESSAGE;
        }catch(Exception e){
            message = "Ocorreu um erro ao atualizar os dados do cliente...\n\n" + e.getMessage().split("\n")[0];
            title = "Erro";
            type = JOptionPane.ERROR_MESSAGE;
        }finally{
            JOptionPane.showMessageDialog(null,message,title,type);
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jCBClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBClientesItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            if(jBEditar.getText() == "Cancelar"){
                toggleEnabled();
                jBEditar.setText("Editar");
            }
            new ClienteController().showCliente(this);
        }
    }//GEN-LAST:event_jCBClientesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<Cliente> jCBClientes;
    private javax.swing.JComboBox<String> jCBPacotes;
    private javax.swing.JLabel jLDtnasc;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPacotes;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JTextField jTFDtnasc;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFTelefone;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JTextField getjTFDtnasc() {
        return jTFDtnasc;
    }

    public javax.swing.JTextField getjTFEmail() {
        return jTFEmail;
    }

    public javax.swing.JTextField getjTFEndereco() {
        return jTFEndereco;
    }

    public javax.swing.JTextField getjTFNome() {
        return jTFNome;
    }

    public javax.swing.JTextField getjTFTelefone() {
        return jTFTelefone;
    }

    public javax.swing.JComboBox<Cliente> getjCBClientes() {
        return jCBClientes;
    }

    public javax.swing.JComboBox<String> getjCBPacotes() {
        return jCBPacotes;
    }
}
